services:
  - type: web
    name: mcp-redmine
    env: docker
    region: frankfurt  # EU region (closest to France)
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: APP_URL
        value: https://mcp-redmine.onrender.com  # Will be updated with your custom domain
      - key: GOOGLE_CLIENT_ID
        sync: false  # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false  # Set manually in Render dashboard
      - key: ENCRYPTION_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_EMAIL_DOMAINS
        sync: false  # Set manually: comma-separated domains (e.g., "company.com,example.org")
      - key: ALLOWED_EMAILS
        sync: false  # Set manually: comma-separated emails (e.g., "alice@example.com,bob@example.com")
      - key: DATABASE_URL
        fromDatabase:
          name: redmine-mcp
          property: connectionString
    healthCheckPath: /health
